ques 26

In [28]:
import numpy as np
l=list(i for i in range(1,10))
ar1=np.array(l)
ar2=np.array([[1,2,3,4,5],[2,4,6,8,10]])
d=ar1.ndim
print ("1st Array: ",ar1)
print("Dimension: ",d)
print ("2nd Array: \n",ar2)
print("Dimension: ",ar2.ndim)
print("Shape: ",ar2.size)
print("Element type: ",ar2.dtype)


1st Array:  [1 2 3 4 5 6 7 8 9]
Dimension:  1
2nd Array: 
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Dimension:  2
Shape:  10
Element type:  int64


Ques 27

In [27]:
ar1=np.array([[1,2,3,4,5],[2,4,6,8,10]])
ar2=np.array([[11,22,33,44,55],[0,0,0,0,0]])
s=np.sum(ar1)
t=np.sum(ar2)
print("Sum of two arrays: \n",ar1+ar2)

print("Difference of two arrays: \n",ar1-ar2)
print("Sum of all elements of ar1 : ",s)
print("Sum of all elements of ar2 : ",t)

Sum of two arrays: 
 [[12 24 36 48 60]
 [ 2  4  6  8 10]]
Difference of two arrays: 
 [[-10 -20 -30 -40 -50]
 [  2   4   6   8  10]]
Sum of all elements of ar1 :  45
Sum of all elements of ar2 :  165


**Ques 29**

In [ ]:
arr=np.array([[4, 16, 25, 36, 49 ],[9,81, 121, 49, 36]])
ar1=np.array([[1,2,-1,2,0 ],[1,0,1,2,0]])

sqrt1=np.sqrt(arr) 
arr6=np.transpose(arr)     

print("Multiplication of Arrays :", arr*ar1)
print("\n\n-> 2D array arr5 = \n",arr, "\nSquare root of elements : \n", sqrt1)
print("\n-> Transpose of 2d array : \n", arr6)

**QUES 30**

In [35]:

matrix=np.array([[2,3,4,5,6],[2,4,5,6,7],[7,8,9,2,1],[5,7,8,9,2],[11,22,33,44,55]])
print("Row Slicing: ", matrix[0:3])
print("Column Slicing: ", matrix[0:,2:4 ])
print("Combined Slicing: ", matrix[0:6:2, -1:-5:-2 ])

Row Slicing:  [[2 3 4 5 6]
 [2 4 5 6 7]
 [7 8 9 2 1]]
Column Slicing:  [[ 4  5]
 [ 5  6]
 [ 9  2]
 [ 8  9]
 [33 44]]
Combined Slicing:  [[ 6  4]
 [ 1  9]
 [55 33]]


In [ ]:
from numpy.lib.function_base import add_newdoc_ufunc
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1, arr2)
print("\n->addition:",arr1+arr2)
print("\n->multiplication:",arr1*arr2)
print("\n->substraction:",arr1-arr2)
np.add(arr1, arr2)
arr3=np.array([7,8,9,10])
arr4=np.array([11,22,33,44])
np.add(arr3,arr4)
arr6=np.array([[4,5],[1,2,]])
#arr6=arr1+5
#print(arr1+5)

arr5=np.array([[4, 16, 25, 36, 49 ],[9,81, 121, 49, 36]])
sum1=np.sum(arr5)
sqrt1=np.sqrt(arr5)  #square root ehehehe
arr6=np.transpose(arr5)     #TRANSPOSE HEHE
matrix=np.array([[2,3,4,5,6],[2,4,5,6,7],[7,8,9,2,1],[5,7,8,9,2],[11,22,33,44,55]])
#
print("\n\n-> 😀2D array arr5 = ",arr5, "\nSum of elements of 2D array5 =", sum1, "\nSquare root of elements : ", sqrt1)
print("\n-> 😊Transpose of 2d array : \n", arr6)
print("\n-> 🤗Slicing of arr1 : ", arr1[2:5])
print("\n->😎 Slicing of arr5 : \n", arr5[2:, 2:])
print("\n->😈Slicing of BIG BOY MATRIX : \n", matrix[0: , 0:6:2 ])

[1 2 3 4 5] [ 6  7  8  9 10]

->addition: [ 7  9 11 13 15]

->multiplication: [ 6 14 24 36 50]

->substraction: [-5 -5 -5 -5 -5]


-> 😀2D array arr5 =  [[  4  16  25  36  49]
 [  9  81 121  49  36]] 
Sum of elements of 2D array5 = 426 
Square root of elements :  [[ 2.  4.  5.  6.  7.]
 [ 3.  9. 11.  7.  6.]]

-> 😊Transpose of 2d array : 
 [[  4   9]
 [ 16  81]
 [ 25 121]
 [ 36  49]
 [ 49  36]]

-> 🤗Slicing of arr1 :  [3 4 5]

->😎 Slicing of arr5 : 
 []

->😈Slicing of BIG BOY MATRIX : 
 [[ 2  4  6]
 [ 2  5  7]
 [ 7  9  1]
 [ 5  8  2]
 [11 33 55]]


In [ ]:
i=0
while i<10:
  print("hehe o-o")
  i+=1


hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o
hehe o-o


In [ ]:
a=2.5
a*=2.6
print(a)

6.5


In [ ]:
a=2
b=3.000
c=a+b
print("c = ", c)
print("c = ", int(c))
print("ID of a = ", id(a))
print("ID of b = ", id(b))
print("ID of c = ", id(c))

c =  5.0
c =  5
ID of a =  11256096
ID of b =  140016105322640
ID of c =  140016105321776
